"""empty message

Revision ID: 070f0a6baa77
Revises: 9775679c42c5
Create Date: 2022-11-05 21:07:09.063775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070f0a6baa77'
down_revision = '9775679c42c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
